### ISSUE TITLE
hspec-contrib-0.3 fails test suite with hspec-2.4 (retry broken?)

### ISSUE THREAD

**Issue by DanBurton** [hspec/hspec#307]
Seen on stackage build server, reproduced locally:

```
hspec-contrib-0.3.0: test (suite: spec)

Progress: 6/7
Test.Hspec.Contrib.HUnit
  fromHUnitTest
    works for a TestCase
    works for a labeled TestCase
    works for a TestCase with nested labels
    works for a flat TestList
    works for a nested TestList
Test.Hspec.Contrib.Retry
  retry test
    retry 11 times, then check the value FAILED [1]

Failures:

  test/Test/Hspec/Contrib/RetrySpec.hs:21:
  1) Test.Hspec.Contrib.Retry, retry test, retry 11 times, then check the value
       expected: 10
        but got: 0

Randomized with seed 516920774
```

How I reproduced:

```
$ stack unpack hspec-contrib-0.3
$ cd hspec-contrib-0.3
$ <<add the following stack.yaml>>
$ stack test
```

```yaml
# stack.yaml
resolver: nightly-2016-02-10
packages:
- '.'
extra-deps:
- hspec-core-2.4.1
- hspec-2.4.1
- hspec-discover-2.4.1
- hspec-expectations-0.8.2
- call-stack-0.1.0
```
